name: ml-benchmark
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.0.0
  - cudatoolkit=11.8
  - pip:
    - transformers>=4.30.0
    - datasets>=2.13.0
    - pydantic>=2.0.0
    - psutil>=5.9.0
    - pynvml>=11.5.0
    - pyRAPL>=0.2.3
    - pandas>=2.0.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - jinja2>=3.1.0
    - pyyaml>=6.0
    - pytest>=7.3.0
    - pytest-cov>=4.1.0
    - pandoc>=2.3
    - python-pptx>=0.6.21
