repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
        exclude: |
            (?x)^(
                data/cached/.*|
                Literature/.*\.pdf
            )$
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
            (?x)^(
                data/cached/models--.*/.no_exist/.*\.json|
                examples/.*\.ipynb
            )$

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.262'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, pydantic]
        exclude: '^tests/'
        args: [--config-file=mypy.ini]

-   repo: local
    hooks:
    -   id: manifest-check
        name: Check artifact manifest
        entry: python src/manifest.py verify --manifest release/manifest.json
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
